// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_runs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const attachCoveredAgentRuns = `-- name: AttachCoveredAgentRuns :execrows
INSERT INTO session_agent_runs (session_id, agent_run_id)
SELECT ws.id, ar.id
FROM agent_runs ar
JOIN work_sessions ws
  ON ws.user_id    = ar.user_id
 AND ws.deleted_at IS NULL
 AND ws.ended_at   IS NOT NULL
 AND ar.started_at >= ws.started_at
 AND ar.started_at <  ws.ended_at
LEFT JOIN session_agent_runs sar ON sar.agent_run_id = ar.id
WHERE ar.user_id = $1
  AND sar.agent_run_id IS NULL
ON CONFLICT DO NOTHING
`

// Attach every unattached run whose START falls inside a finished session.
//
// The range is half-open — [started_at, ended_at) — unlike the commit lookup,
// which uses a closed range. A closed range lets a run sitting exactly on a
// boundary match both the session that ends there and the one that begins
// there, and StartSession deliberately butts sessions up against each other a
// microsecond apart. Half-open makes that impossible rather than unlikely.
func (q *Queries) AttachCoveredAgentRuns(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, attachCoveredAgentRuns, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const detachAgentRunsFromSession = `-- name: DetachAgentRunsFromSession :execrows
DELETE FROM session_agent_runs WHERE session_id = $1
`

func (q *Queries) DetachAgentRunsFromSession(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, detachAgentRunsFromSession, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const detachUncoveredAgentRuns = `-- name: DetachUncoveredAgentRuns :execrows
DELETE FROM session_agent_runs sar
USING agent_runs ar, work_sessions ws
WHERE sar.agent_run_id = ar.id
  AND sar.session_id   = ws.id
  AND ar.user_id       = $1
  AND NOT (
        ws.deleted_at IS NULL
    AND ws.ended_at   IS NOT NULL
    AND ar.started_at >= ws.started_at
    AND ar.started_at <  ws.ended_at
  )
`

// Release runs whose session no longer covers them.
//
// Editing a session's times is the whole reason this exists: shrink a session
// and the runs it used to hold have to become unmatched again, or they stay
// filed under a stretch of work that no longer claims them.
func (q *Queries) DetachUncoveredAgentRuns(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, detachUncoveredAgentRuns, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAgentRun = `-- name: InsertAgentRun :one

INSERT INTO agent_runs (
    id, user_id, tool, external_id, started_at, ended_at,
    model, cwd, repo_full_name, tool_calls
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (user_id, tool, external_id) DO NOTHING
RETURNING id, user_id, tool, external_id, started_at, ended_at, model, cwd, repo_full_name, tool_calls, created_at
`

type InsertAgentRunParams struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	Tool         string    `json:"tool"`
	ExternalID   string    `json:"external_id"`
	StartedAt    time.Time `json:"started_at"`
	EndedAt      time.Time `json:"ended_at"`
	Model        string    `json:"model"`
	Cwd          string    `json:"cwd"`
	RepoFullName string    `json:"repo_full_name"`
	ToolCalls    *int32    `json:"tool_calls"`
}

// Agent runs -----------------------------------------------------------------
// Insert, or say nothing if this run is already known.
//
// DO NOTHING rather than DO UPDATE: the queue is flushed at-least-once and a
// resend carries the same facts, so there is nothing to refresh. Returning no
// row on conflict is how the caller counts duplicates without a second query.
func (q *Queries) InsertAgentRun(ctx context.Context, arg InsertAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, insertAgentRun,
		arg.ID,
		arg.UserID,
		arg.Tool,
		arg.ExternalID,
		arg.StartedAt,
		arg.EndedAt,
		arg.Model,
		arg.Cwd,
		arg.RepoFullName,
		arg.ToolCalls,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tool,
		&i.ExternalID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Model,
		&i.Cwd,
		&i.RepoFullName,
		&i.ToolCalls,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentRunsForSession = `-- name: ListAgentRunsForSession :many
SELECT ar.id, ar.user_id, ar.tool, ar.external_id, ar.started_at, ar.ended_at, ar.model, ar.cwd, ar.repo_full_name, ar.tool_calls, ar.created_at FROM agent_runs ar
JOIN session_agent_runs sar ON sar.agent_run_id = ar.id
WHERE sar.session_id = $1
ORDER BY ar.started_at ASC
`

func (q *Queries) ListAgentRunsForSession(ctx context.Context, sessionID uuid.UUID) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, listAgentRunsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRun{}
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Tool,
			&i.ExternalID,
			&i.StartedAt,
			&i.EndedAt,
			&i.Model,
			&i.Cwd,
			&i.RepoFullName,
			&i.ToolCalls,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentRunsInWindow = `-- name: ListAgentRunsInWindow :many
SELECT id, user_id, tool, external_id, started_at, ended_at, model, cwd, repo_full_name, tool_calls, created_at FROM agent_runs
WHERE user_id = $1
  AND started_at >= $2::timestamptz
  AND started_at <= $3::timestamptz
ORDER BY started_at ASC
`

type ListAgentRunsInWindowParams struct {
	UserID uuid.UUID `json:"user_id"`
	FromTs time.Time `json:"from_ts"`
	ToTs   time.Time `json:"to_ts"`
}

// Every run in a window, matched or not — the feed behind the day view, where
// what actually ran is drawn under what was declared.
func (q *Queries) ListAgentRunsInWindow(ctx context.Context, arg ListAgentRunsInWindowParams) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, listAgentRunsInWindow, arg.UserID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRun{}
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Tool,
			&i.ExternalID,
			&i.StartedAt,
			&i.EndedAt,
			&i.Model,
			&i.Cwd,
			&i.RepoFullName,
			&i.ToolCalls,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnmatchedAgentRuns = `-- name: ListUnmatchedAgentRuns :many
SELECT ar.id, ar.user_id, ar.tool, ar.external_id, ar.started_at, ar.ended_at, ar.model, ar.cwd, ar.repo_full_name, ar.tool_calls, ar.created_at FROM agent_runs ar
LEFT JOIN session_agent_runs sar ON sar.agent_run_id = ar.id
WHERE ar.user_id = $1
  AND sar.agent_run_id IS NULL
  AND ar.started_at >= $2::timestamptz
  AND ar.started_at <= $3::timestamptz
ORDER BY ar.started_at ASC
`

type ListUnmatchedAgentRunsParams struct {
	UserID uuid.UUID `json:"user_id"`
	FromTs time.Time `json:"from_ts"`
	ToTs   time.Time `json:"to_ts"`
}

// Runs in the window that belong to no session: the feed behind "an agent was
// working here and no timer was running".
func (q *Queries) ListUnmatchedAgentRuns(ctx context.Context, arg ListUnmatchedAgentRunsParams) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, listUnmatchedAgentRuns, arg.UserID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRun{}
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Tool,
			&i.ExternalID,
			&i.StartedAt,
			&i.EndedAt,
			&i.Model,
			&i.Cwd,
			&i.RepoFullName,
			&i.ToolCalls,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
