// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveTokens = `-- name: CountActiveTokens :one
SELECT count(*) FROM api_tokens WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) CountActiveTokens(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTokens, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (id, user_id, name, token_hash, token_prefix, scope, scoped_project_ids, expires_at, kind)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, name, token_hash, token_prefix, scope, kind, scoped_project_ids, created_at, expires_at, last_used_at, revoked_at
`

type CreateAPITokenParams struct {
	ID               uuid.UUID   `json:"id"`
	UserID           uuid.UUID   `json:"user_id"`
	Name             string      `json:"name"`
	TokenHash        []byte      `json:"token_hash"`
	TokenPrefix      string      `json:"token_prefix"`
	Scope            string      `json:"scope"`
	ScopedProjectIds []uuid.UUID `json:"scoped_project_ids"`
	ExpiresAt        *time.Time  `json:"expires_at"`
	Kind             string      `json:"kind"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Scope,
		arg.ScopedProjectIds,
		arg.ExpiresAt,
		arg.Kind,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scope,
		&i.Kind,
		&i.ScopedProjectIds,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT api_tokens.id, api_tokens.user_id, api_tokens.name, api_tokens.token_hash, api_tokens.token_prefix, api_tokens.scope, api_tokens.kind, api_tokens.scoped_project_ids, api_tokens.created_at, api_tokens.expires_at, api_tokens.last_used_at, api_tokens.revoked_at, users.id, users.email, users.password_hash, users.email_verified_at, users.display_name, users.avatar_url, users.timezone, users.google_sub, users.github_id, users.apple_sub, users.totp_secret_enc, users.totp_enabled, users.created_at, users.updated_at, users.deleted_at
FROM api_tokens
JOIN users ON users.id = api_tokens.user_id
WHERE api_tokens.token_hash = $1
  AND api_tokens.revoked_at IS NULL
  AND (api_tokens.expires_at IS NULL OR api_tokens.expires_at > now())
  AND users.deleted_at IS NULL
`

type GetAPITokenByHashRow struct {
	ApiToken ApiToken `json:"api_token"`
	User     User     `json:"user"`
}

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash []byte) (GetAPITokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i GetAPITokenByHashRow
	err := row.Scan(
		&i.ApiToken.ID,
		&i.ApiToken.UserID,
		&i.ApiToken.Name,
		&i.ApiToken.TokenHash,
		&i.ApiToken.TokenPrefix,
		&i.ApiToken.Scope,
		&i.ApiToken.Kind,
		&i.ApiToken.ScopedProjectIds,
		&i.ApiToken.CreatedAt,
		&i.ApiToken.ExpiresAt,
		&i.ApiToken.LastUsedAt,
		&i.ApiToken.RevokedAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.EmailVerifiedAt,
		&i.User.DisplayName,
		&i.User.AvatarUrl,
		&i.User.Timezone,
		&i.User.GoogleSub,
		&i.User.GithubID,
		&i.User.AppleSub,
		&i.User.TotpSecretEnc,
		&i.User.TotpEnabled,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.DeletedAt,
	)
	return i, err
}

const listTokensByUser = `-- name: ListTokensByUser :many
SELECT id, user_id, name, token_hash, token_prefix, scope, kind, scoped_project_ids, created_at, expires_at, last_used_at, revoked_at FROM api_tokens
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListTokensByUser(ctx context.Context, userID uuid.UUID) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.Scope,
			&i.Kind,
			&i.ScopedProjectIds,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
UPDATE api_tokens SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeAPITokenParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}
