// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (id, user_id, action, ip, metadata)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditLogParams struct {
	ID       uuid.UUID  `json:"id"`
	UserID   *uuid.UUID `json:"user_id"`
	Action   string     `json:"action"`
	Ip       *string    `json:"ip"`
	Metadata []byte     `json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.UserID,
		arg.Action,
		arg.Ip,
		arg.Metadata,
	)
	return err
}

const listAuditForUser = `-- name: ListAuditForUser :many
SELECT id, user_id, action, ip, metadata, created_at FROM audit_log
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAuditForUserParams struct {
	UserID *uuid.UUID `json:"user_id"`
	Limit  int32      `json:"limit"`
}

func (q *Queries) ListAuditForUser(ctx context.Context, arg ListAuditForUserParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Ip,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
