// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (id, user_id, token_hash, expires_at, absolute_expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, token_hash, created_at, expires_at, absolute_expires_at, last_seen_at, ip, user_agent, revoked_at
`

type CreateAuthSessionParams struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	TokenHash         []byte    `json:"token_hash"`
	ExpiresAt         time.Time `json:"expires_at"`
	AbsoluteExpiresAt time.Time `json:"absolute_expires_at"`
	Ip                *string   `json:"ip"`
	UserAgent         *string   `json:"user_agent"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.LastSeenAt,
		&i.Ip,
		&i.UserAgent,
		&i.RevokedAt,
	)
	return i, err
}

const deleteStaleAuthSessions = `-- name: DeleteStaleAuthSessions :execrows
DELETE FROM auth_sessions
WHERE absolute_expires_at < now()
   OR (revoked_at IS NOT NULL AND revoked_at < now() - interval '30 days')
`

func (q *Queries) DeleteStaleAuthSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleAuthSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthSessionByHash = `-- name: GetAuthSessionByHash :one
SELECT auth_sessions.id, auth_sessions.user_id, auth_sessions.token_hash, auth_sessions.created_at, auth_sessions.expires_at, auth_sessions.absolute_expires_at, auth_sessions.last_seen_at, auth_sessions.ip, auth_sessions.user_agent, auth_sessions.revoked_at, users.id, users.email, users.password_hash, users.email_verified_at, users.display_name, users.avatar_url, users.timezone, users.google_sub, users.github_id, users.apple_sub, users.totp_secret_enc, users.totp_enabled, users.created_at, users.updated_at, users.deleted_at
FROM auth_sessions
JOIN users ON users.id = auth_sessions.user_id
WHERE auth_sessions.token_hash = $1
  AND auth_sessions.revoked_at IS NULL
  AND auth_sessions.expires_at > now()
  AND auth_sessions.absolute_expires_at > now()
  AND users.deleted_at IS NULL
`

type GetAuthSessionByHashRow struct {
	AuthSession AuthSession `json:"auth_session"`
	User        User        `json:"user"`
}

func (q *Queries) GetAuthSessionByHash(ctx context.Context, tokenHash []byte) (GetAuthSessionByHashRow, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByHash, tokenHash)
	var i GetAuthSessionByHashRow
	err := row.Scan(
		&i.AuthSession.ID,
		&i.AuthSession.UserID,
		&i.AuthSession.TokenHash,
		&i.AuthSession.CreatedAt,
		&i.AuthSession.ExpiresAt,
		&i.AuthSession.AbsoluteExpiresAt,
		&i.AuthSession.LastSeenAt,
		&i.AuthSession.Ip,
		&i.AuthSession.UserAgent,
		&i.AuthSession.RevokedAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.EmailVerifiedAt,
		&i.User.DisplayName,
		&i.User.AvatarUrl,
		&i.User.Timezone,
		&i.User.GoogleSub,
		&i.User.GithubID,
		&i.User.AppleSub,
		&i.User.TotpSecretEnc,
		&i.User.TotpEnabled,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.DeletedAt,
	)
	return i, err
}

const listAuthSessionsByUser = `-- name: ListAuthSessionsByUser :many
SELECT id, user_id, token_hash, created_at, expires_at, absolute_expires_at, last_seen_at, ip, user_agent, revoked_at FROM auth_sessions
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
ORDER BY last_seen_at DESC
`

func (q *Queries) ListAuthSessionsByUser(ctx context.Context, userID uuid.UUID) ([]AuthSession, error) {
	rows, err := q.db.Query(ctx, listAuthSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthSession{}
	for rows.Next() {
		var i AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AbsoluteExpiresAt,
			&i.LastSeenAt,
			&i.Ip,
			&i.UserAgent,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserAuthSessions = `-- name: RevokeAllUserAuthSessions :exec
UPDATE auth_sessions SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserAuthSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserAuthSessions, userID)
	return err
}

const revokeAuthSession = `-- name: RevokeAuthSession :execrows
UPDATE auth_sessions SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeAuthSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOtherUserAuthSessions = `-- name: RevokeOtherUserAuthSessions :exec
UPDATE auth_sessions SET revoked_at = now()
WHERE user_id = $1 AND id <> $2 AND revoked_at IS NULL
`

type RevokeOtherUserAuthSessionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) RevokeOtherUserAuthSessions(ctx context.Context, arg RevokeOtherUserAuthSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOtherUserAuthSessions, arg.UserID, arg.ID)
	return err
}

const touchAuthSession = `-- name: TouchAuthSession :exec
UPDATE auth_sessions SET last_seen_at = now(), expires_at = $2 WHERE id = $1
`

type TouchAuthSessionParams struct {
	ID        uuid.UUID `json:"id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) TouchAuthSession(ctx context.Context, arg TouchAuthSessionParams) error {
	_, err := q.db.Exec(ctx, touchAuthSession, arg.ID, arg.ExpiresAt)
	return err
}
