// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimDueDeliveries = `-- name: ClaimDueDeliveries :many
SELECT id, webhook_id, event_id, attempt, status, response_status, response_body_snippet, error, delivered_at, next_retry_at, created_at FROM webhook_deliveries
WHERE status IN ('pending', 'failed') AND next_retry_at IS NOT NULL AND next_retry_at <= now()
ORDER BY next_retry_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimDueDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, claimDueDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventID,
			&i.Attempt,
			&i.Status,
			&i.ResponseStatus,
			&i.ResponseBodySnippet,
			&i.Error,
			&i.DeliveredAt,
			&i.NextRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO webhook_deliveries (id, webhook_id, event_id, status, next_retry_at)
VALUES ($1, $2, $3, 'pending', now())
RETURNING id, webhook_id, event_id, attempt, status, response_status, response_body_snippet, error, delivered_at, next_retry_at, created_at
`

type CreateDeliveryParams struct {
	ID        uuid.UUID `json:"id"`
	WebhookID uuid.UUID `json:"webhook_id"`
	EventID   uuid.UUID `json:"event_id"`
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createDelivery, arg.ID, arg.WebhookID, arg.EventID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventID,
		&i.Attempt,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBodySnippet,
		&i.Error,
		&i.DeliveredAt,
		&i.NextRetryAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDelivery = `-- name: GetDelivery :one
SELECT id, webhook_id, event_id, attempt, status, response_status, response_body_snippet, error, delivered_at, next_retry_at, created_at FROM webhook_deliveries WHERE id = $1
`

func (q *Queries) GetDelivery(ctx context.Context, id uuid.UUID) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getDelivery, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventID,
		&i.Attempt,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBodySnippet,
		&i.Error,
		&i.DeliveredAt,
		&i.NextRetryAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDeliveriesForWebhook = `-- name: ListDeliveriesForWebhook :many
SELECT id, webhook_id, event_id, attempt, status, response_status, response_body_snippet, error, delivered_at, next_retry_at, created_at FROM webhook_deliveries WHERE webhook_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListDeliveriesForWebhookParams struct {
	WebhookID uuid.UUID `json:"webhook_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListDeliveriesForWebhook(ctx context.Context, arg ListDeliveriesForWebhookParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveriesForWebhook, arg.WebhookID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventID,
			&i.Attempt,
			&i.Status,
			&i.ResponseStatus,
			&i.ResponseBodySnippet,
			&i.Error,
			&i.DeliveredAt,
			&i.NextRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeliveryResult = `-- name: UpdateDeliveryResult :exec
UPDATE webhook_deliveries SET
    status = $2, attempt = $3, response_status = $4,
    response_body_snippet = $5, error = $6, delivered_at = $7, next_retry_at = $8
WHERE id = $1
`

type UpdateDeliveryResultParams struct {
	ID                  uuid.UUID  `json:"id"`
	Status              string     `json:"status"`
	Attempt             int32      `json:"attempt"`
	ResponseStatus      *int32     `json:"response_status"`
	ResponseBodySnippet *string    `json:"response_body_snippet"`
	Error               *string    `json:"error"`
	DeliveredAt         *time.Time `json:"delivered_at"`
	NextRetryAt         *time.Time `json:"next_retry_at"`
}

func (q *Queries) UpdateDeliveryResult(ctx context.Context, arg UpdateDeliveryResultParams) error {
	_, err := q.db.Exec(ctx, updateDeliveryResult,
		arg.ID,
		arg.Status,
		arg.Attempt,
		arg.ResponseStatus,
		arg.ResponseBodySnippet,
		arg.Error,
		arg.DeliveredAt,
		arg.NextRetryAt,
	)
	return err
}
