// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmailToken = `-- name: CreateEmailToken :one
INSERT INTO email_tokens (id, user_id, kind, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, kind, token_hash, created_at, expires_at, used_at
`

type CreateEmailTokenParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Kind      string    `json:"kind"`
	TokenHash []byte    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRow(ctx, createEmailToken,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const deleteUserEmailTokens = `-- name: DeleteUserEmailTokens :exec
DELETE FROM email_tokens WHERE user_id = $1 AND kind = $2
`

type DeleteUserEmailTokensParams struct {
	UserID uuid.UUID `json:"user_id"`
	Kind   string    `json:"kind"`
}

func (q *Queries) DeleteUserEmailTokens(ctx context.Context, arg DeleteUserEmailTokensParams) error {
	_, err := q.db.Exec(ctx, deleteUserEmailTokens, arg.UserID, arg.Kind)
	return err
}

const getValidEmailToken = `-- name: GetValidEmailToken :one
SELECT id, user_id, kind, token_hash, created_at, expires_at, used_at FROM email_tokens
WHERE token_hash = $1 AND kind = $2 AND used_at IS NULL AND expires_at > now()
`

type GetValidEmailTokenParams struct {
	TokenHash []byte `json:"token_hash"`
	Kind      string `json:"kind"`
}

func (q *Queries) GetValidEmailToken(ctx context.Context, arg GetValidEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRow(ctx, getValidEmailToken, arg.TokenHash, arg.Kind)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const markEmailTokenUsed = `-- name: MarkEmailTokenUsed :execrows
UPDATE email_tokens SET used_at = now() WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) MarkEmailTokenUsed(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailTokenUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
