// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const claimUnprocessedEvents = `-- name: ClaimUnprocessedEvents :many
SELECT id, seq, type, user_id, project_id, actor, payload, created_at, processed_at FROM events
WHERE processed_at IS NULL
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimUnprocessedEvents(ctx context.Context, limit int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, claimUnprocessedEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Type,
			&i.UserID,
			&i.ProjectID,
			&i.Actor,
			&i.Payload,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvent = `-- name: GetEvent :one
SELECT id, seq, type, user_id, project_id, actor, payload, created_at, processed_at FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.Type,
		&i.UserID,
		&i.ProjectID,
		&i.Actor,
		&i.Payload,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (id, type, user_id, project_id, actor, payload)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, seq, type, user_id, project_id, actor, payload, created_at, processed_at
`

type InsertEventParams struct {
	ID        uuid.UUID  `json:"id"`
	Type      string     `json:"type"`
	UserID    uuid.UUID  `json:"user_id"`
	ProjectID *uuid.UUID `json:"project_id"`
	Actor     *string    `json:"actor"`
	Payload   []byte     `json:"payload"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.ID,
		arg.Type,
		arg.UserID,
		arg.ProjectID,
		arg.Actor,
		arg.Payload,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.Type,
		&i.UserID,
		&i.ProjectID,
		&i.Actor,
		&i.Payload,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const listEventsForUserAfterSeq = `-- name: ListEventsForUserAfterSeq :many

SELECT id, seq, type, user_id, project_id, actor, payload, created_at, processed_at FROM events
WHERE user_id = $1
  AND seq > $2
  AND created_at < now() - make_interval(secs => $3::double precision)
ORDER BY seq ASC
LIMIT $4
`

type ListEventsForUserAfterSeqParams struct {
	UserID    uuid.UUID `json:"user_id"`
	AfterSeq  int64     `json:"after_seq"`
	GraceSecs float64   `json:"grace_secs"`
	Lim       int32     `json:"lim"`
}

// Delta feed + SSE cursor reads (docs/offline-sync.md §5). The grace window is
// the seq gap-safety guard: bigserial values are allocated at INSERT, so a
// still-uncommitted transaction can hold a smaller seq than rows already
// visible; excluding very fresh rows keeps a forward-only cursor from skipping
// them permanently.
func (q *Queries) ListEventsForUserAfterSeq(ctx context.Context, arg ListEventsForUserAfterSeqParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsForUserAfterSeq,
		arg.UserID,
		arg.AfterSeq,
		arg.GraceSecs,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Type,
			&i.UserID,
			&i.ProjectID,
			&i.Actor,
			&i.Payload,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
UPDATE events SET processed_at = now() WHERE id = $1
`

func (q *Queries) MarkEventProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEventProcessed, id)
	return err
}

const maxEventSeq = `-- name: MaxEventSeq :one
SELECT COALESCE(max(seq), 0)::bigint FROM events
WHERE created_at < now() - make_interval(secs => $1::double precision)
`

func (q *Queries) MaxEventSeq(ctx context.Context, graceSecs float64) (int64, error) {
	row := q.db.QueryRow(ctx, maxEventSeq, graceSecs)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const minEventSeq = `-- name: MinEventSeq :one
SELECT COALESCE(min(seq), 0)::bigint FROM events
`

func (q *Queries) MinEventSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, minEventSeq)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const purgeOldEvents = `-- name: PurgeOldEvents :execrows
DELETE FROM events WHERE created_at < now() - interval '30 days'
`

func (q *Queries) PurgeOldEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOldEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
