// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addGitHubEmail = `-- name: AddGitHubEmail :exec
INSERT INTO github_emails (user_id, email) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddGitHubEmailParams struct {
	UserID uuid.UUID `json:"user_id"`
	Email  string    `json:"email"`
}

func (q *Queries) AddGitHubEmail(ctx context.Context, arg AddGitHubEmailParams) error {
	_, err := q.db.Exec(ctx, addGitHubEmail, arg.UserID, arg.Email)
	return err
}

const attachCommitToSession = `-- name: AttachCommitToSession :execrows
INSERT INTO session_commits (session_id, commit_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AttachCommitToSessionParams struct {
	SessionID uuid.UUID `json:"session_id"`
	CommitID  uuid.UUID `json:"commit_id"`
}

func (q *Queries) AttachCommitToSession(ctx context.Context, arg AttachCommitToSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachCommitToSession, arg.SessionID, arg.CommitID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimStaleGitHubConnections = `-- name: ClaimStaleGitHubConnections :many
SELECT user_id FROM github_connections
WHERE revoked_at IS NULL
  AND (last_scan_at IS NULL OR last_scan_at <= $1::timestamptz)
ORDER BY last_scan_at ASC NULLS FIRST
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ClaimStaleGitHubConnectionsParams struct {
	Before time.Time `json:"before"`
	Lim    int32     `json:"lim"`
}

// Connections whose commits have not been fetched recently.
//
// The session queue only ever holds sessions, so an account that has not
// recorded one is never scanned — which is exactly a new account, on the day
// it most needs to see something. This claims accounts instead: the ones that
// have never been scanned first, then the ones that have gone stale.
func (q *Queries) ClaimStaleGitHubConnections(ctx context.Context, arg ClaimStaleGitHubConnectionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, claimStaleGitHubConnections, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCommitsForSessions = `-- name: CountCommitsForSessions :many
SELECT sc.session_id, count(*)::bigint AS n
FROM session_commits sc
WHERE sc.session_id = ANY($1::uuid[])
GROUP BY sc.session_id
`

type CountCommitsForSessionsRow struct {
	SessionID uuid.UUID `json:"session_id"`
	N         int64     `json:"n"`
}

func (q *Queries) CountCommitsForSessions(ctx context.Context, sessionIds []uuid.UUID) ([]CountCommitsForSessionsRow, error) {
	rows, err := q.db.Query(ctx, countCommitsForSessions, sessionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCommitsForSessionsRow{}
	for rows.Next() {
		var i CountCommitsForSessionsRow
		if err := rows.Scan(&i.SessionID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteGitHubConnection = `-- name: DeleteGitHubConnection :execrows
DELETE FROM github_connections WHERE user_id = $1
`

func (q *Queries) DeleteGitHubConnection(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGitHubConnection, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGitHubEmail = `-- name: DeleteGitHubEmail :execrows
DELETE FROM github_emails WHERE user_id = $1 AND email = $2
`

type DeleteGitHubEmailParams struct {
	UserID uuid.UUID `json:"user_id"`
	Email  string    `json:"email"`
}

func (q *Queries) DeleteGitHubEmail(ctx context.Context, arg DeleteGitHubEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGitHubEmail, arg.UserID, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const detachCommit = `-- name: DetachCommit :execrows
DELETE FROM session_commits WHERE session_id = $1 AND commit_id = $2
`

type DetachCommitParams struct {
	SessionID uuid.UUID `json:"session_id"`
	CommitID  uuid.UUID `json:"commit_id"`
}

func (q *Queries) DetachCommit(ctx context.Context, arg DetachCommitParams) (int64, error) {
	result, err := q.db.Exec(ctx, detachCommit, arg.SessionID, arg.CommitID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const detachCommitsFromSession = `-- name: DetachCommitsFromSession :execrows
DELETE FROM session_commits WHERE session_id = $1
`

func (q *Queries) DetachCommitsFromSession(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, detachCommitsFromSession, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGitHubConnection = `-- name: GetGitHubConnection :one
SELECT user_id, github_login, access_token_enc, scopes, connected_at, last_scan_at, last_error, revoked_at FROM github_connections WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) GetGitHubConnection(ctx context.Context, userID uuid.UUID) (GithubConnection, error) {
	row := q.db.QueryRow(ctx, getGitHubConnection, userID)
	var i GithubConnection
	err := row.Scan(
		&i.UserID,
		&i.GithubLogin,
		&i.AccessTokenEnc,
		&i.Scopes,
		&i.ConnectedAt,
		&i.LastScanAt,
		&i.LastError,
		&i.RevokedAt,
	)
	return i, err
}

const listCommitsForSession = `-- name: ListCommitsForSession :many
SELECT c.id, c.user_id, c.repo_full_name, c.sha, c.message, c.committed_at, c.url, c.additions, c.deletions, c.created_at FROM commits c
JOIN session_commits sc ON sc.commit_id = c.id
WHERE sc.session_id = $1
ORDER BY c.committed_at ASC
`

func (q *Queries) ListCommitsForSession(ctx context.Context, sessionID uuid.UUID) ([]Commit, error) {
	rows, err := q.db.Query(ctx, listCommitsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Commit{}
	for rows.Next() {
		var i Commit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RepoFullName,
			&i.Sha,
			&i.Message,
			&i.CommittedAt,
			&i.Url,
			&i.Additions,
			&i.Deletions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommitsInWindow = `-- name: ListCommitsInWindow :many
SELECT id, user_id, repo_full_name, sha, message, committed_at, url, additions, deletions, created_at FROM commits
WHERE user_id = $1
  AND committed_at >= $2::timestamptz
  AND committed_at <= $3::timestamptz
ORDER BY committed_at ASC
`

type ListCommitsInWindowParams struct {
	UserID uuid.UUID `json:"user_id"`
	FromTs time.Time `json:"from_ts"`
	ToTs   time.Time `json:"to_ts"`
}

func (q *Queries) ListCommitsInWindow(ctx context.Context, arg ListCommitsInWindowParams) ([]Commit, error) {
	rows, err := q.db.Query(ctx, listCommitsInWindow, arg.UserID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Commit{}
	for rows.Next() {
		var i Commit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RepoFullName,
			&i.Sha,
			&i.Message,
			&i.CommittedAt,
			&i.Url,
			&i.Additions,
			&i.Deletions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitHubEmails = `-- name: ListGitHubEmails :many
SELECT email FROM github_emails WHERE user_id = $1 ORDER BY email
`

func (q *Queries) ListGitHubEmails(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listGitHubEmails, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnmatchedCommits = `-- name: ListUnmatchedCommits :many
SELECT c.id, c.user_id, c.repo_full_name, c.sha, c.message, c.committed_at, c.url, c.additions, c.deletions, c.created_at FROM commits c
LEFT JOIN session_commits sc ON sc.commit_id = c.id
WHERE c.user_id = $1
  AND sc.commit_id IS NULL
  AND c.committed_at >= $2::timestamptz
  AND c.committed_at <= $3::timestamptz
ORDER BY c.committed_at ASC
`

type ListUnmatchedCommitsParams struct {
	UserID uuid.UUID `json:"user_id"`
	FromTs time.Time `json:"from_ts"`
	ToTs   time.Time `json:"to_ts"`
}

// Commits in the window that belong to no session. This is the feed behind
// "unmatched commits": work that happened while no timer was running.
func (q *Queries) ListUnmatchedCommits(ctx context.Context, arg ListUnmatchedCommitsParams) ([]Commit, error) {
	rows, err := q.db.Query(ctx, listUnmatchedCommits, arg.UserID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Commit{}
	for rows.Next() {
		var i Commit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RepoFullName,
			&i.Sha,
			&i.Message,
			&i.CommittedAt,
			&i.Url,
			&i.Additions,
			&i.Deletions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGitHubError = `-- name: SetGitHubError :exec
UPDATE github_connections SET last_error = $2 WHERE user_id = $1
`

type SetGitHubErrorParams struct {
	UserID    uuid.UUID `json:"user_id"`
	LastError *string   `json:"last_error"`
}

func (q *Queries) SetGitHubError(ctx context.Context, arg SetGitHubErrorParams) error {
	_, err := q.db.Exec(ctx, setGitHubError, arg.UserID, arg.LastError)
	return err
}

const touchGitHubScan = `-- name: TouchGitHubScan :exec
UPDATE github_connections SET last_scan_at = now(), last_error = NULL WHERE user_id = $1
`

func (q *Queries) TouchGitHubScan(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchGitHubScan, userID)
	return err
}

const upsertCommit = `-- name: UpsertCommit :one

INSERT INTO commits (id, user_id, repo_full_name, sha, message, committed_at, url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, repo_full_name, sha) DO UPDATE SET
    message = EXCLUDED.message,
    url     = EXCLUDED.url
RETURNING id, user_id, repo_full_name, sha, message, committed_at, url, additions, deletions, created_at
`

type UpsertCommitParams struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RepoFullName string    `json:"repo_full_name"`
	Sha          string    `json:"sha"`
	Message      string    `json:"message"`
	CommittedAt  time.Time `json:"committed_at"`
	Url          string    `json:"url"`
}

// Commits ------------------------------------------------------------------
// Upsert so a re-scan of the same window is free of duplicates. The message and
// URL are refreshed because an amended commit keeps its position in history but
// not its text.
func (q *Queries) UpsertCommit(ctx context.Context, arg UpsertCommitParams) (Commit, error) {
	row := q.db.QueryRow(ctx, upsertCommit,
		arg.ID,
		arg.UserID,
		arg.RepoFullName,
		arg.Sha,
		arg.Message,
		arg.CommittedAt,
		arg.Url,
	)
	var i Commit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoFullName,
		&i.Sha,
		&i.Message,
		&i.CommittedAt,
		&i.Url,
		&i.Additions,
		&i.Deletions,
		&i.CreatedAt,
	)
	return i, err
}

const upsertGitHubConnection = `-- name: UpsertGitHubConnection :one
INSERT INTO github_connections (user_id, github_login, access_token_enc, scopes)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    github_login     = EXCLUDED.github_login,
    access_token_enc = EXCLUDED.access_token_enc,
    scopes           = EXCLUDED.scopes,
    connected_at     = now(),
    last_error       = NULL,
    revoked_at       = NULL
RETURNING user_id, github_login, access_token_enc, scopes, connected_at, last_scan_at, last_error, revoked_at
`

type UpsertGitHubConnectionParams struct {
	UserID         uuid.UUID `json:"user_id"`
	GithubLogin    string    `json:"github_login"`
	AccessTokenEnc []byte    `json:"access_token_enc"`
	Scopes         string    `json:"scopes"`
}

func (q *Queries) UpsertGitHubConnection(ctx context.Context, arg UpsertGitHubConnectionParams) (GithubConnection, error) {
	row := q.db.QueryRow(ctx, upsertGitHubConnection,
		arg.UserID,
		arg.GithubLogin,
		arg.AccessTokenEnc,
		arg.Scopes,
	)
	var i GithubConnection
	err := row.Scan(
		&i.UserID,
		&i.GithubLogin,
		&i.AccessTokenEnc,
		&i.Scopes,
		&i.ConnectedAt,
		&i.LastScanAt,
		&i.LastError,
		&i.RevokedAt,
	)
	return i, err
}
