// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package db

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1::int AS ok
`

// Trivial connectivity probe so the sqlc pipeline is exercised end-to-end in
// Phase 0. Real domain queries (lists, tasks, ...) arrive in Phase 2.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
