// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :execrows
INSERT INTO idempotency_keys (user_id, key, request_hash, response_status, response_body)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, key) DO NOTHING
`

type CreateIdempotencyKeyParams struct {
	UserID         uuid.UUID `json:"user_id"`
	Key            string    `json:"key"`
	RequestHash    []byte    `json:"request_hash"`
	ResponseStatus int32     `json:"response_status"`
	ResponseBody   []byte    `json:"response_body"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, createIdempotencyKey,
		arg.UserID,
		arg.Key,
		arg.RequestHash,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE created_at < now() - interval '24 hours'
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT user_id, key, request_hash, response_status, response_body, created_at FROM idempotency_keys WHERE user_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	UserID uuid.UUID `json:"user_id"`
	Key    string    `json:"key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.UserID,
		&i.Key,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}
