// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type ApiToken struct {
	ID               uuid.UUID   `json:"id"`
	UserID           uuid.UUID   `json:"user_id"`
	Name             string      `json:"name"`
	TokenHash        []byte      `json:"token_hash"`
	TokenPrefix      string      `json:"token_prefix"`
	Scope            string      `json:"scope"`
	Kind             string      `json:"kind"`
	ScopedProjectIds []uuid.UUID `json:"scoped_project_ids"`
	CreatedAt        time.Time   `json:"created_at"`
	ExpiresAt        *time.Time  `json:"expires_at"`
	LastUsedAt       *time.Time  `json:"last_used_at"`
	RevokedAt        *time.Time  `json:"revoked_at"`
}

type AuditLog struct {
	ID        uuid.UUID  `json:"id"`
	UserID    *uuid.UUID `json:"user_id"`
	Action    string     `json:"action"`
	Ip        *string    `json:"ip"`
	Metadata  []byte     `json:"metadata"`
	CreatedAt time.Time  `json:"created_at"`
}

type AuthSession struct {
	ID                uuid.UUID  `json:"id"`
	UserID            uuid.UUID  `json:"user_id"`
	TokenHash         []byte     `json:"token_hash"`
	CreatedAt         time.Time  `json:"created_at"`
	ExpiresAt         time.Time  `json:"expires_at"`
	AbsoluteExpiresAt time.Time  `json:"absolute_expires_at"`
	LastSeenAt        time.Time  `json:"last_seen_at"`
	Ip                *string    `json:"ip"`
	UserAgent         *string    `json:"user_agent"`
	RevokedAt         *time.Time `json:"revoked_at"`
}

type Commit struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RepoFullName string    `json:"repo_full_name"`
	Sha          string    `json:"sha"`
	Message      string    `json:"message"`
	CommittedAt  time.Time `json:"committed_at"`
	Url          string    `json:"url"`
	Additions    *int32    `json:"additions"`
	Deletions    *int32    `json:"deletions"`
	CreatedAt    time.Time `json:"created_at"`
}

type EmailToken struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	Kind      string     `json:"kind"`
	TokenHash []byte     `json:"token_hash"`
	CreatedAt time.Time  `json:"created_at"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
}

type Event struct {
	ID          uuid.UUID  `json:"id"`
	Seq         int64      `json:"seq"`
	Type        string     `json:"type"`
	UserID      uuid.UUID  `json:"user_id"`
	ProjectID   *uuid.UUID `json:"project_id"`
	Actor       *string    `json:"actor"`
	Payload     []byte     `json:"payload"`
	CreatedAt   time.Time  `json:"created_at"`
	ProcessedAt *time.Time `json:"processed_at"`
}

type GithubConnection struct {
	UserID         uuid.UUID  `json:"user_id"`
	GithubLogin    string     `json:"github_login"`
	AccessTokenEnc []byte     `json:"access_token_enc"`
	Scopes         string     `json:"scopes"`
	ConnectedAt    time.Time  `json:"connected_at"`
	LastScanAt     *time.Time `json:"last_scan_at"`
	LastError      *string    `json:"last_error"`
	RevokedAt      *time.Time `json:"revoked_at"`
}

type GithubEmail struct {
	UserID uuid.UUID `json:"user_id"`
	Email  string    `json:"email"`
}

type IdempotencyKey struct {
	UserID         uuid.UUID `json:"user_id"`
	Key            string    `json:"key"`
	RequestHash    []byte    `json:"request_hash"`
	ResponseStatus int32     `json:"response_status"`
	ResponseBody   []byte    `json:"response_body"`
	CreatedAt      time.Time `json:"created_at"`
}

type Project struct {
	ID              uuid.UUID  `json:"id"`
	OwnerID         uuid.UUID  `json:"owner_id"`
	Name            string     `json:"name"`
	Client          string     `json:"client"`
	Color           *string    `json:"color"`
	HourlyRateCents *int64     `json:"hourly_rate_cents"`
	Currency        string     `json:"currency"`
	Billable        bool       `json:"billable"`
	ArchivedAt      *time.Time `json:"archived_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
}

type ProjectRepo struct {
	ID         uuid.UUID  `json:"id"`
	ProjectID  uuid.UUID  `json:"project_id"`
	Provider   string     `json:"provider"`
	FullName   string     `json:"full_name"`
	Branches   []byte     `json:"branches"`
	BranchesAt *time.Time `json:"branches_at"`
	CreatedAt  time.Time  `json:"created_at"`
}

type SessionCommit struct {
	SessionID uuid.UUID `json:"session_id"`
	CommitID  uuid.UUID `json:"commit_id"`
	CreatedAt time.Time `json:"created_at"`
}

type TwoFactorRecoveryCode struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	CodeHash  []byte     `json:"code_hash"`
	UsedAt    *time.Time `json:"used_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type User struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisplayName     *string    `json:"display_name"`
	AvatarUrl       *string    `json:"avatar_url"`
	Timezone        string     `json:"timezone"`
	GoogleSub       *string    `json:"google_sub"`
	GithubID        *string    `json:"github_id"`
	AppleSub        *string    `json:"apple_sub"`
	TotpSecretEnc   []byte     `json:"totp_secret_enc"`
	TotpEnabled     bool       `json:"totp_enabled"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
}

type Webhook struct {
	ID                  uuid.UUID  `json:"id"`
	UserID              uuid.UUID  `json:"user_id"`
	Url                 string     `json:"url"`
	SecretEncrypted     []byte     `json:"secret_encrypted"`
	Events              []byte     `json:"events"`
	Active              bool       `json:"active"`
	CreatedAt           time.Time  `json:"created_at"`
	DisabledAt          *time.Time `json:"disabled_at"`
	DisabledReason      *string    `json:"disabled_reason"`
	ConsecutiveFailures int32      `json:"consecutive_failures"`
}

type WebhookDelivery struct {
	ID                  uuid.UUID  `json:"id"`
	WebhookID           uuid.UUID  `json:"webhook_id"`
	EventID             uuid.UUID  `json:"event_id"`
	Attempt             int32      `json:"attempt"`
	Status              string     `json:"status"`
	ResponseStatus      *int32     `json:"response_status"`
	ResponseBodySnippet *string    `json:"response_body_snippet"`
	Error               *string    `json:"error"`
	DeliveredAt         *time.Time `json:"delivered_at"`
	NextRetryAt         *time.Time `json:"next_retry_at"`
	CreatedAt           time.Time  `json:"created_at"`
}

type WorkSession struct {
	ID           uuid.UUID  `json:"id"`
	ProjectID    uuid.UUID  `json:"project_id"`
	UserID       uuid.UUID  `json:"user_id"`
	Note         string     `json:"note"`
	StartedAt    time.Time  `json:"started_at"`
	EndedAt      *time.Time `json:"ended_at"`
	Source       string     `json:"source"`
	SyncState    string     `json:"sync_state"`
	SyncAttempts int16      `json:"sync_attempts"`
	SyncNextAt   *time.Time `json:"sync_next_at"`
	SyncError    *string    `json:"sync_error"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
}
