// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const archiveProject = `-- name: ArchiveProject :one
UPDATE projects SET archived_at = now(), updated_at = now()
WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL AND archived_at IS NULL
RETURNING id, owner_id, name, client, color, hourly_rate_cents, currency, billable, archived_at, created_at, updated_at, deleted_at
`

type ArchiveProjectParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, archiveProject, arg.ID, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Client,
		&i.Color,
		&i.HourlyRateCents,
		&i.Currency,
		&i.Billable,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countSessionsForProject = `-- name: CountSessionsForProject :one
SELECT count(*) FROM work_sessions
WHERE project_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountSessionsForProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionsForProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, owner_id, name, client, color, hourly_rate_cents, currency, billable)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, owner_id, name, client, color, hourly_rate_cents, currency, billable, archived_at, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	ID              uuid.UUID `json:"id"`
	OwnerID         uuid.UUID `json:"owner_id"`
	Name            string    `json:"name"`
	Client          string    `json:"client"`
	Color           *string   `json:"color"`
	HourlyRateCents *int64    `json:"hourly_rate_cents"`
	Currency        string    `json:"currency"`
	Billable        bool      `json:"billable"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Client,
		arg.Color,
		arg.HourlyRateCents,
		arg.Currency,
		arg.Billable,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Client,
		&i.Color,
		&i.HourlyRateCents,
		&i.Currency,
		&i.Billable,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProjectRepo = `-- name: DeleteProjectRepo :execrows
DELETE FROM project_repos
USING projects
WHERE project_repos.id = $1
  AND project_repos.project_id = projects.id
  AND projects.owner_id = $2
`

type DeleteProjectRepoParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) DeleteProjectRepo(ctx context.Context, arg DeleteProjectRepoParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectRepo, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectForUser = `-- name: GetProjectForUser :one
SELECT id, owner_id, name, client, color, hourly_rate_cents, currency, billable, archived_at, created_at, updated_at, deleted_at FROM projects
WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
`

type GetProjectForUserParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) GetProjectForUser(ctx context.Context, arg GetProjectForUserParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectForUser, arg.ID, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Client,
		&i.Color,
		&i.HourlyRateCents,
		&i.Currency,
		&i.Billable,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectRepo = `-- name: GetProjectRepo :one
SELECT project_repos.id, project_repos.project_id, project_repos.provider, project_repos.full_name, project_repos.branches, project_repos.branches_at, project_repos.created_at FROM project_repos
JOIN projects ON projects.id = project_repos.project_id
WHERE project_repos.id = $1 AND projects.owner_id = $2 AND projects.deleted_at IS NULL
`

type GetProjectRepoParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) GetProjectRepo(ctx context.Context, arg GetProjectRepoParams) (ProjectRepo, error) {
	row := q.db.QueryRow(ctx, getProjectRepo, arg.ID, arg.OwnerID)
	var i ProjectRepo
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.FullName,
		&i.Branches,
		&i.BranchesAt,
		&i.CreatedAt,
	)
	return i, err
}

const linkProjectRepo = `-- name: LinkProjectRepo :one
INSERT INTO project_repos (id, project_id, provider, full_name)
VALUES ($1, $2, 'github', $3)
ON CONFLICT (project_id, provider, full_name) DO NOTHING
RETURNING id, project_id, provider, full_name, branches, branches_at, created_at
`

type LinkProjectRepoParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	FullName  string    `json:"full_name"`
}

func (q *Queries) LinkProjectRepo(ctx context.Context, arg LinkProjectRepoParams) (ProjectRepo, error) {
	row := q.db.QueryRow(ctx, linkProjectRepo, arg.ID, arg.ProjectID, arg.FullName)
	var i ProjectRepo
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.FullName,
		&i.Branches,
		&i.BranchesAt,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectRepos = `-- name: ListProjectRepos :many
SELECT id, project_id, provider, full_name, branches, branches_at, created_at FROM project_repos WHERE project_id = $1 ORDER BY full_name ASC
`

func (q *Queries) ListProjectRepos(ctx context.Context, projectID uuid.UUID) ([]ProjectRepo, error) {
	rows, err := q.db.Query(ctx, listProjectRepos, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectRepo{}
	for rows.Next() {
		var i ProjectRepo
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Provider,
			&i.FullName,
			&i.Branches,
			&i.BranchesAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, owner_id, name, client, color, hourly_rate_cents, currency, billable, archived_at, created_at, updated_at, deleted_at FROM projects
WHERE owner_id = $1
  AND deleted_at IS NULL
  AND ($2::boolean OR archived_at IS NULL)
ORDER BY lower(name) ASC
`

type ListProjectsParams struct {
	OwnerID         uuid.UUID `json:"owner_id"`
	IncludeArchived bool      `json:"include_archived"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.OwnerID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Client,
			&i.Color,
			&i.HourlyRateCents,
			&i.Currency,
			&i.Billable,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposForUser = `-- name: ListReposForUser :many
SELECT project_repos.id, project_repos.project_id, project_repos.provider, project_repos.full_name, project_repos.branches, project_repos.branches_at, project_repos.created_at FROM project_repos
JOIN projects ON projects.id = project_repos.project_id
WHERE projects.owner_id = $1 AND projects.deleted_at IS NULL
ORDER BY project_repos.full_name ASC
`

func (q *Queries) ListReposForUser(ctx context.Context, ownerID uuid.UUID) ([]ProjectRepo, error) {
	rows, err := q.db.Query(ctx, listReposForUser, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectRepo{}
	for rows.Next() {
		var i ProjectRepo
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Provider,
			&i.FullName,
			&i.Branches,
			&i.BranchesAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectsForRepo = `-- name: ProjectsForRepo :many
SELECT DISTINCT projects.id FROM projects
JOIN project_repos ON project_repos.project_id = projects.id
WHERE projects.owner_id = $1
  AND project_repos.full_name = $2
  AND projects.deleted_at IS NULL
`

type ProjectsForRepoParams struct {
	OwnerID  uuid.UUID `json:"owner_id"`
	FullName string    `json:"full_name"`
}

// Which projects a repository belongs to, for suggesting a project when a
// cluster of unmatched commits is turned into a session.
func (q *Queries) ProjectsForRepo(ctx context.Context, arg ProjectsForRepoParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, projectsForRepo, arg.OwnerID, arg.FullName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRepoBranches = `-- name: SetRepoBranches :exec
UPDATE project_repos SET branches = $2, branches_at = now() WHERE id = $1
`

type SetRepoBranchesParams struct {
	ID       uuid.UUID `json:"id"`
	Branches []byte    `json:"branches"`
}

func (q *Queries) SetRepoBranches(ctx context.Context, arg SetRepoBranchesParams) error {
	_, err := q.db.Exec(ctx, setRepoBranches, arg.ID, arg.Branches)
	return err
}

const softDeleteProject = `-- name: SoftDeleteProject :execrows
UPDATE projects SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
`

type SoftDeleteProjectParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProject, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unarchiveProject = `-- name: UnarchiveProject :one
UPDATE projects SET archived_at = NULL, updated_at = now()
WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
RETURNING id, owner_id, name, client, color, hourly_rate_cents, currency, billable, archived_at, created_at, updated_at, deleted_at
`

type UnarchiveProjectParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) UnarchiveProject(ctx context.Context, arg UnarchiveProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, unarchiveProject, arg.ID, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Client,
		&i.Color,
		&i.HourlyRateCents,
		&i.Currency,
		&i.Billable,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
    name              = coalesce($1, name),
    client            = coalesce($2, client),
    color             = CASE WHEN $3::boolean THEN NULL
                             ELSE coalesce($4, color) END,
    hourly_rate_cents = CASE WHEN $5::boolean THEN NULL
                             ELSE coalesce($6, hourly_rate_cents) END,
    currency          = coalesce($7, currency),
    billable          = coalesce($8, billable),
    updated_at        = now()
WHERE id = $9 AND owner_id = $10 AND deleted_at IS NULL
RETURNING id, owner_id, name, client, color, hourly_rate_cents, currency, billable, archived_at, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	Name            *string   `json:"name"`
	Client          *string   `json:"client"`
	ClearColor      bool      `json:"clear_color"`
	Color           *string   `json:"color"`
	ClearRate       bool      `json:"clear_rate"`
	HourlyRateCents *int64    `json:"hourly_rate_cents"`
	Currency        *string   `json:"currency"`
	Billable        *bool     `json:"billable"`
	ID              uuid.UUID `json:"id"`
	OwnerID         uuid.UUID `json:"owner_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Client,
		arg.ClearColor,
		arg.Color,
		arg.ClearRate,
		arg.HourlyRateCents,
		arg.Currency,
		arg.Billable,
		arg.ID,
		arg.OwnerID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Client,
		&i.Color,
		&i.HourlyRateCents,
		&i.Currency,
		&i.Billable,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
