// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AddGitHubEmail(ctx context.Context, arg AddGitHubEmailParams) error
	AddRecoveryCode(ctx context.Context, arg AddRecoveryCodeParams) error
	ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (Project, error)
	AttachCommitToSession(ctx context.Context, arg AttachCommitToSessionParams) (int64, error)
	ClaimDueDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error)
	// NULL sync_next_at means "due now", and it is how every immediate queueing
	// writes itself. That is not a shortcut — it removes a clock comparison.
	//
	// sync_next_at used to be set to now(), which is the DATABASE's clock, and then
	// compared against a timestamp the Go process captured from ITS clock. On a
	// host whose container clock drifts a few milliseconds ahead, a session queued
	// at stop-time was not yet "due" on the next pass and the scan silently waited
	// a full tick. In tests, which claim immediately, it failed outright — and
	// intermittently, which is the worst way to learn about it.
	//
	// A real timestamp now means only one thing: a backoff deadline, written by the
	// same code that reads it.
	ClaimPendingSyncSessions(ctx context.Context, arg ClaimPendingSyncSessionsParams) ([]WorkSession, error)
	ClaimUnprocessedEvents(ctx context.Context, limit int32) ([]Event, error)
	ClearTOTP(ctx context.Context, id uuid.UUID) error
	CountActiveTokens(ctx context.Context, userID uuid.UUID) (int64, error)
	CountCommitsForSessions(ctx context.Context, sessionIds []uuid.UUID) ([]CountCommitsForSessionsRow, error)
	CountSessionsForProject(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountUnusedRecoveryCodes(ctx context.Context, userID uuid.UUID) (int64, error)
	CountWebhooksForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error)
	CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (WebhookDelivery, error)
	CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (EmailToken, error)
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (int64, error)
	// Creates an account linked to a verified social identity. password_hash holds
	// an unusable random hash (the caller has no way to know the plaintext) so the
	// password plane can never authenticate an OAuth-only account. Email is treated
	// as verified because the provider asserted verification.
	CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error)
	DeleteGitHubConnection(ctx context.Context, userID uuid.UUID) (int64, error)
	DeleteGitHubEmail(ctx context.Context, arg DeleteGitHubEmailParams) (int64, error)
	DeleteProjectRepo(ctx context.Context, arg DeleteProjectRepoParams) (int64, error)
	DeleteRecoveryCodes(ctx context.Context, userID uuid.UUID) error
	DeleteStaleAuthSessions(ctx context.Context) (int64, error)
	DeleteUserEmailTokens(ctx context.Context, arg DeleteUserEmailTokensParams) error
	DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) (int64, error)
	DetachCommit(ctx context.Context, arg DetachCommitParams) (int64, error)
	DetachCommitsFromSession(ctx context.Context, sessionID uuid.UUID) (int64, error)
	DisableWebhook(ctx context.Context, arg DisableWebhookParams) error
	GetAPITokenByHash(ctx context.Context, tokenHash []byte) (GetAPITokenByHashRow, error)
	GetAuthSessionByHash(ctx context.Context, tokenHash []byte) (GetAuthSessionByHashRow, error)
	GetDelivery(ctx context.Context, id uuid.UUID) (WebhookDelivery, error)
	GetEvent(ctx context.Context, id uuid.UUID) (Event, error)
	GetGitHubConnection(ctx context.Context, userID uuid.UUID) (GithubConnection, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetOpenWorkSession(ctx context.Context, userID uuid.UUID) (WorkSession, error)
	GetProjectForUser(ctx context.Context, arg GetProjectForUserParams) (Project, error)
	GetProjectRepo(ctx context.Context, arg GetProjectRepoParams) (ProjectRepo, error)
	GetUserByAppleSub(ctx context.Context, appleSub *string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGithubID(ctx context.Context, githubID *string) (User, error)
	GetUserByGoogleSub(ctx context.Context, googleSub *string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetValidEmailToken(ctx context.Context, arg GetValidEmailTokenParams) (EmailToken, error)
	GetWebhook(ctx context.Context, id uuid.UUID) (Webhook, error)
	GetWorkSession(ctx context.Context, arg GetWorkSessionParams) (WorkSession, error)
	HardDeleteUser(ctx context.Context, id uuid.UUID) error
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error)
	LinkAppleSub(ctx context.Context, arg LinkAppleSubParams) error
	LinkGithubID(ctx context.Context, arg LinkGithubIDParams) error
	LinkGoogleSub(ctx context.Context, arg LinkGoogleSubParams) error
	LinkProjectRepo(ctx context.Context, arg LinkProjectRepoParams) (ProjectRepo, error)
	ListActiveWebhooksForUser(ctx context.Context, arg ListActiveWebhooksForUserParams) ([]Webhook, error)
	ListAuditForUser(ctx context.Context, arg ListAuditForUserParams) ([]AuditLog, error)
	ListAuthSessionsByUser(ctx context.Context, userID uuid.UUID) ([]AuthSession, error)
	ListCommitsForSession(ctx context.Context, sessionID uuid.UUID) ([]Commit, error)
	ListCommitsInWindow(ctx context.Context, arg ListCommitsInWindowParams) ([]Commit, error)
	ListDeliveriesForWebhook(ctx context.Context, arg ListDeliveriesForWebhookParams) ([]WebhookDelivery, error)
	// Delta feed + SSE cursor reads (docs/offline-sync.md §5). The grace window is
	// the seq gap-safety guard: bigserial values are allocated at INSERT, so a
	// still-uncommitted transaction can hold a smaller seq than rows already
	// visible; excluding very fresh rows keeps a forward-only cursor from skipping
	// them permanently.
	ListEventsForUserAfterSeq(ctx context.Context, arg ListEventsForUserAfterSeqParams) ([]Event, error)
	ListGitHubEmails(ctx context.Context, userID uuid.UUID) ([]string, error)
	ListProjectRepos(ctx context.Context, projectID uuid.UUID) ([]ProjectRepo, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListReposForUser(ctx context.Context, ownerID uuid.UUID) ([]ProjectRepo, error)
	ListTokensByUser(ctx context.Context, userID uuid.UUID) ([]ApiToken, error)
	// Commits in the window that belong to no session. This is the feed behind
	// "unmatched commits": work that happened while no timer was running.
	ListUnmatchedCommits(ctx context.Context, arg ListUnmatchedCommitsParams) ([]Commit, error)
	ListWebhooksForUser(ctx context.Context, arg ListWebhooksForUserParams) ([]Webhook, error)
	ListWorkSessions(ctx context.Context, arg ListWorkSessionsParams) ([]WorkSession, error)
	MarkEmailTokenUsed(ctx context.Context, id uuid.UUID) (int64, error)
	MarkEmailVerified(ctx context.Context, id uuid.UUID) error
	MarkEventProcessed(ctx context.Context, id uuid.UUID) error
	MarkSessionSyncPending(ctx context.Context, arg MarkSessionSyncPendingParams) error
	MarkSessionsSyncPendingSince(ctx context.Context, since time.Time) (int64, error)
	MaxEventSeq(ctx context.Context, graceSecs float64) (int64, error)
	MinEventSeq(ctx context.Context) (int64, error)
	// Trivial connectivity probe so the sqlc pipeline is exercised end-to-end in
	// Phase 0. Real domain queries (lists, tasks, ...) arrive in Phase 2.
	Ping(ctx context.Context) (int32, error)
	// Which projects a repository belongs to, for suggesting a project when a
	// cluster of unmatched commits is turned into a session.
	ProjectsForRepo(ctx context.Context, arg ProjectsForRepoParams) ([]uuid.UUID, error)
	PurgeOldEvents(ctx context.Context) (int64, error)
	RecordWebhookFailure(ctx context.Context, id uuid.UUID) (int32, error)
	RecordWebhookSuccess(ctx context.Context, id uuid.UUID) error
	RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error)
	RevokeAllUserAuthSessions(ctx context.Context, userID uuid.UUID) error
	RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (int64, error)
	RevokeOtherUserAuthSessions(ctx context.Context, arg RevokeOtherUserAuthSessionsParams) error
	RotateWebhookSecret(ctx context.Context, arg RotateWebhookSecretParams) (Webhook, error)
	// Which session covers an instant. Ranges cannot overlap, so this returns at
	// most one row.
	SessionCovering(ctx context.Context, arg SessionCoveringParams) (WorkSession, error)
	SetGitHubError(ctx context.Context, arg SetGitHubErrorParams) error
	SetRepoBranches(ctx context.Context, arg SetRepoBranchesParams) error
	SetSessionSyncFailed(ctx context.Context, arg SetSessionSyncFailedParams) error
	SetSessionSyncOK(ctx context.Context, id uuid.UUID) error
	SetSessionSyncRetry(ctx context.Context, arg SetSessionSyncRetryParams) error
	SetSessionSyncSkipped(ctx context.Context, arg SetSessionSyncSkippedParams) (int64, error)
	SetTOTPEnabled(ctx context.Context, arg SetTOTPEnabledParams) error
	SetTOTPSecret(ctx context.Context, arg SetTOTPSecretParams) error
	SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (int64, error)
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	SoftDeleteWorkSession(ctx context.Context, arg SoftDeleteWorkSessionParams) (int64, error)
	StartWorkSession(ctx context.Context, arg StartWorkSessionParams) (WorkSession, error)
	// Closes whichever session is currently open for this user. Called in the same
	// transaction as StartWorkSession so a "start" that replaces a running timer is
	// atomic: there is never an instant with two open sessions, which is what the
	// one_open_session_per_user index would reject anyway.
	//
	// The GREATEST is the range CHECK's guard: ended_at must be strictly after
	// started_at, so a stop that lands on (or before) the start is nudged one
	// microsecond forward rather than failing. A microsecond, not a second — with a
	// second, replacing a timer less than a second old would push its end PAST the
	// new session's start and the two would overlap, which is exactly what commit
	// attribution cannot survive. The caller reads the returned ended_at back and
	// starts the next session there, so the two abut exactly.
	StopOpenSessionForUser(ctx context.Context, arg StopOpenSessionForUserParams) ([]WorkSession, error)
	StopWorkSession(ctx context.Context, arg StopWorkSessionParams) (WorkSession, error)
	// Day buckets are cut in the caller's timezone, not UTC: a session that runs
	// 22:30–23:30 UTC belongs to the next local day in Istanbul, and a report that
	// says otherwise is simply wrong to the person reading it.
	SummaryByDay(ctx context.Context, arg SummaryByDayParams) ([]SummaryByDayRow, error)
	// Reports ------------------------------------------------------------------
	SummaryByProject(ctx context.Context, arg SummaryByProjectParams) ([]SummaryByProjectRow, error)
	TouchAPIToken(ctx context.Context, id uuid.UUID) error
	TouchAuthSession(ctx context.Context, arg TouchAuthSessionParams) error
	TouchGitHubScan(ctx context.Context, userID uuid.UUID) error
	UnarchiveProject(ctx context.Context, arg UnarchiveProjectParams) (Project, error)
	UpdateDeliveryResult(ctx context.Context, arg UpdateDeliveryResultParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error)
	UpdateWorkSession(ctx context.Context, arg UpdateWorkSessionParams) (WorkSession, error)
	// Commits ------------------------------------------------------------------
	// Upsert so a re-scan of the same window is free of duplicates. The message and
	// URL are refreshed because an amended commit keeps its position in history but
	// not its text.
	UpsertCommit(ctx context.Context, arg UpsertCommitParams) (Commit, error)
	UpsertGitHubConnection(ctx context.Context, arg UpsertGitHubConnectionParams) (GithubConnection, error)
	UseRecoveryCode(ctx context.Context, arg UseRecoveryCodeParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
