// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addRecoveryCode = `-- name: AddRecoveryCode :exec
INSERT INTO two_factor_recovery_codes (id, user_id, code_hash) VALUES ($1, $2, $3)
`

type AddRecoveryCodeParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	CodeHash []byte    `json:"code_hash"`
}

func (q *Queries) AddRecoveryCode(ctx context.Context, arg AddRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, addRecoveryCode, arg.ID, arg.UserID, arg.CodeHash)
	return err
}

const clearTOTP = `-- name: ClearTOTP :exec
UPDATE users SET totp_secret_enc = NULL, totp_enabled = false, updated_at = now() WHERE id = $1
`

func (q *Queries) ClearTOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearTOTP, id)
	return err
}

const countUnusedRecoveryCodes = `-- name: CountUnusedRecoveryCodes :one
SELECT count(*) FROM two_factor_recovery_codes WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) CountUnusedRecoveryCodes(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnusedRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOAuthUser = `-- name: CreateOAuthUser :one
INSERT INTO users (id, email, password_hash, email_verified_at, google_sub, github_id, apple_sub)
VALUES ($1, $2, $3, now(), $4, $5, $6)
RETURNING id, email, password_hash, email_verified_at, display_name, avatar_url, timezone, google_sub, github_id, apple_sub, totp_secret_enc, totp_enabled, created_at, updated_at, deleted_at
`

type CreateOAuthUserParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	GoogleSub    *string   `json:"google_sub"`
	GithubID     *string   `json:"github_id"`
	AppleSub     *string   `json:"apple_sub"`
}

// Creates an account linked to a verified social identity. password_hash holds
// an unusable random hash (the caller has no way to know the plaintext) so the
// password plane can never authenticate an OAuth-only account. Email is treated
// as verified because the provider asserted verification.
func (q *Queries) CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createOAuthUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.GoogleSub,
		arg.GithubID,
		arg.AppleSub,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.GoogleSub,
		&i.GithubID,
		&i.AppleSub,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, email_verified_at, display_name, avatar_url, timezone, google_sub, github_id, apple_sub, totp_secret_enc, totp_enabled, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.GoogleSub,
		&i.GithubID,
		&i.AppleSub,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM two_factor_recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodes, userID)
	return err
}

const getUserByAppleSub = `-- name: GetUserByAppleSub :one
SELECT id, email, password_hash, email_verified_at, display_name, avatar_url, timezone, google_sub, github_id, apple_sub, totp_secret_enc, totp_enabled, created_at, updated_at, deleted_at FROM users WHERE apple_sub = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByAppleSub(ctx context.Context, appleSub *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAppleSub, appleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.GoogleSub,
		&i.GithubID,
		&i.AppleSub,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, email_verified_at, display_name, avatar_url, timezone, google_sub, github_id, apple_sub, totp_secret_enc, totp_enabled, created_at, updated_at, deleted_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.GoogleSub,
		&i.GithubID,
		&i.AppleSub,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByGithubID = `-- name: GetUserByGithubID :one
SELECT id, email, password_hash, email_verified_at, display_name, avatar_url, timezone, google_sub, github_id, apple_sub, totp_secret_enc, totp_enabled, created_at, updated_at, deleted_at FROM users WHERE github_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByGithubID(ctx context.Context, githubID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGithubID, githubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.GoogleSub,
		&i.GithubID,
		&i.AppleSub,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id, email, password_hash, email_verified_at, display_name, avatar_url, timezone, google_sub, github_id, apple_sub, totp_secret_enc, totp_enabled, created_at, updated_at, deleted_at FROM users WHERE google_sub = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.GoogleSub,
		&i.GithubID,
		&i.AppleSub,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, email_verified_at, display_name, avatar_url, timezone, google_sub, github_id, apple_sub, totp_secret_enc, totp_enabled, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.GoogleSub,
		&i.GithubID,
		&i.AppleSub,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteUser = `-- name: HardDeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) HardDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteUser, id)
	return err
}

const linkAppleSub = `-- name: LinkAppleSub :exec
UPDATE users
SET apple_sub = $2, email_verified_at = COALESCE(email_verified_at, now()), updated_at = now()
WHERE id = $1
`

type LinkAppleSubParams struct {
	ID       uuid.UUID `json:"id"`
	AppleSub *string   `json:"apple_sub"`
}

func (q *Queries) LinkAppleSub(ctx context.Context, arg LinkAppleSubParams) error {
	_, err := q.db.Exec(ctx, linkAppleSub, arg.ID, arg.AppleSub)
	return err
}

const linkGithubID = `-- name: LinkGithubID :exec
UPDATE users
SET github_id = $2, email_verified_at = COALESCE(email_verified_at, now()), updated_at = now()
WHERE id = $1
`

type LinkGithubIDParams struct {
	ID       uuid.UUID `json:"id"`
	GithubID *string   `json:"github_id"`
}

func (q *Queries) LinkGithubID(ctx context.Context, arg LinkGithubIDParams) error {
	_, err := q.db.Exec(ctx, linkGithubID, arg.ID, arg.GithubID)
	return err
}

const linkGoogleSub = `-- name: LinkGoogleSub :exec
UPDATE users
SET google_sub = $2, email_verified_at = COALESCE(email_verified_at, now()), updated_at = now()
WHERE id = $1
`

type LinkGoogleSubParams struct {
	ID        uuid.UUID `json:"id"`
	GoogleSub *string   `json:"google_sub"`
}

func (q *Queries) LinkGoogleSub(ctx context.Context, arg LinkGoogleSubParams) error {
	_, err := q.db.Exec(ctx, linkGoogleSub, arg.ID, arg.GoogleSub)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users SET email_verified_at = now(), updated_at = now()
WHERE id = $1 AND email_verified_at IS NULL
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const setTOTPEnabled = `-- name: SetTOTPEnabled :exec
UPDATE users SET totp_enabled = $2, updated_at = now() WHERE id = $1
`

type SetTOTPEnabledParams struct {
	ID          uuid.UUID `json:"id"`
	TotpEnabled bool      `json:"totp_enabled"`
}

func (q *Queries) SetTOTPEnabled(ctx context.Context, arg SetTOTPEnabledParams) error {
	_, err := q.db.Exec(ctx, setTOTPEnabled, arg.ID, arg.TotpEnabled)
	return err
}

const setTOTPSecret = `-- name: SetTOTPSecret :exec
UPDATE users SET totp_secret_enc = $2, updated_at = now() WHERE id = $1
`

type SetTOTPSecretParams struct {
	ID            uuid.UUID `json:"id"`
	TotpSecretEnc []byte    `json:"totp_secret_enc"`
}

func (q *Queries) SetTOTPSecret(ctx context.Context, arg SetTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, setTOTPSecret, arg.ID, arg.TotpSecretEnc)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE users SET avatar_url = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, email_verified_at, display_name, avatar_url, timezone, google_sub, github_id, apple_sub, totp_secret_enc, totp_enabled, created_at, updated_at, deleted_at
`

type UpdateUserAvatarParams struct {
	ID        uuid.UUID `json:"id"`
	AvatarUrl *string   `json:"avatar_url"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAvatar, arg.ID, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.GoogleSub,
		&i.GithubID,
		&i.AppleSub,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users SET email = $2, email_verified_at = NULL, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, email_verified_at, display_name, avatar_url, timezone, google_sub, github_id, apple_sub, totp_secret_enc, totp_enabled, created_at, updated_at, deleted_at
`

type UpdateUserEmailParams struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.GoogleSub,
		&i.GithubID,
		&i.AppleSub,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET display_name = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, email_verified_at, display_name, avatar_url, timezone, google_sub, github_id, apple_sub, totp_secret_enc, totp_enabled, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName *string   `json:"display_name"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.GoogleSub,
		&i.GithubID,
		&i.AppleSub,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserTimezone = `-- name: UpdateUserTimezone :one
UPDATE users SET timezone = $2, updated_at = now() WHERE id = $1 RETURNING id, email, password_hash, email_verified_at, display_name, avatar_url, timezone, google_sub, github_id, apple_sub, totp_secret_enc, totp_enabled, created_at, updated_at, deleted_at
`

type UpdateUserTimezoneParams struct {
	ID       uuid.UUID `json:"id"`
	Timezone string    `json:"timezone"`
}

func (q *Queries) UpdateUserTimezone(ctx context.Context, arg UpdateUserTimezoneParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserTimezone, arg.ID, arg.Timezone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.GoogleSub,
		&i.GithubID,
		&i.AppleSub,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const useRecoveryCode = `-- name: UseRecoveryCode :execrows
UPDATE two_factor_recovery_codes SET used_at = now()
WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
`

type UseRecoveryCodeParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CodeHash []byte    `json:"code_hash"`
}

func (q *Queries) UseRecoveryCode(ctx context.Context, arg UseRecoveryCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, useRecoveryCode, arg.UserID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
