// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countWebhooksForUser = `-- name: CountWebhooksForUser :one
SELECT count(*) FROM webhooks WHERE user_id = $1
`

func (q *Queries) CountWebhooksForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhooksForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (id, user_id, url, secret_encrypted, events)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, url, secret_encrypted, events, active, created_at, disabled_at, disabled_reason, consecutive_failures
`

type CreateWebhookParams struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	Url             string    `json:"url"`
	SecretEncrypted []byte    `json:"secret_encrypted"`
	Events          []byte    `json:"events"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.ID,
		arg.UserID,
		arg.Url,
		arg.SecretEncrypted,
		arg.Events,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.SecretEncrypted,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :execrows
DELETE FROM webhooks WHERE id = $1 AND user_id = $2
`

type DeleteWebhookParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhook, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableWebhook = `-- name: DisableWebhook :exec
UPDATE webhooks SET active = false, disabled_at = now(), disabled_reason = $2 WHERE id = $1
`

type DisableWebhookParams struct {
	ID             uuid.UUID `json:"id"`
	DisabledReason *string   `json:"disabled_reason"`
}

func (q *Queries) DisableWebhook(ctx context.Context, arg DisableWebhookParams) error {
	_, err := q.db.Exec(ctx, disableWebhook, arg.ID, arg.DisabledReason)
	return err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, user_id, url, secret_encrypted, events, active, created_at, disabled_at, disabled_reason, consecutive_failures FROM webhooks WHERE id = $1
`

func (q *Queries) GetWebhook(ctx context.Context, id uuid.UUID) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.SecretEncrypted,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const listActiveWebhooksForUser = `-- name: ListActiveWebhooksForUser :many
SELECT id, user_id, url, secret_encrypted, events, active, created_at, disabled_at, disabled_reason, consecutive_failures FROM webhooks WHERE user_id = $1 AND active = true LIMIT $2
`

type ListActiveWebhooksForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Lim    int32     `json:"lim"`
}

func (q *Queries) ListActiveWebhooksForUser(ctx context.Context, arg ListActiveWebhooksForUserParams) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listActiveWebhooksForUser, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.SecretEncrypted,
			&i.Events,
			&i.Active,
			&i.CreatedAt,
			&i.DisabledAt,
			&i.DisabledReason,
			&i.ConsecutiveFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksForUser = `-- name: ListWebhooksForUser :many
SELECT id, user_id, url, secret_encrypted, events, active, created_at, disabled_at, disabled_reason, consecutive_failures FROM webhooks WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListWebhooksForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Lim    int32     `json:"lim"`
}

func (q *Queries) ListWebhooksForUser(ctx context.Context, arg ListWebhooksForUserParams) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksForUser, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.SecretEncrypted,
			&i.Events,
			&i.Active,
			&i.CreatedAt,
			&i.DisabledAt,
			&i.DisabledReason,
			&i.ConsecutiveFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordWebhookFailure = `-- name: RecordWebhookFailure :one
UPDATE webhooks SET consecutive_failures = consecutive_failures + 1 WHERE id = $1
RETURNING consecutive_failures
`

func (q *Queries) RecordWebhookFailure(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, recordWebhookFailure, id)
	var consecutive_failures int32
	err := row.Scan(&consecutive_failures)
	return consecutive_failures, err
}

const recordWebhookSuccess = `-- name: RecordWebhookSuccess :exec
UPDATE webhooks SET consecutive_failures = 0 WHERE id = $1
`

func (q *Queries) RecordWebhookSuccess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordWebhookSuccess, id)
	return err
}

const rotateWebhookSecret = `-- name: RotateWebhookSecret :one
UPDATE webhooks SET secret_encrypted = $2 WHERE id = $1 RETURNING id, user_id, url, secret_encrypted, events, active, created_at, disabled_at, disabled_reason, consecutive_failures
`

type RotateWebhookSecretParams struct {
	ID              uuid.UUID `json:"id"`
	SecretEncrypted []byte    `json:"secret_encrypted"`
}

func (q *Queries) RotateWebhookSecret(ctx context.Context, arg RotateWebhookSecretParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, rotateWebhookSecret, arg.ID, arg.SecretEncrypted)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.SecretEncrypted,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks SET
    url = $2,
    events = $3,
    active = $4,
    disabled_at = CASE WHEN $4 THEN NULL ELSE disabled_at END,
    disabled_reason = CASE WHEN $4 THEN NULL ELSE disabled_reason END,
    consecutive_failures = CASE WHEN $4 THEN 0 ELSE consecutive_failures END
WHERE id = $1
RETURNING id, user_id, url, secret_encrypted, events, active, created_at, disabled_at, disabled_reason, consecutive_failures
`

type UpdateWebhookParams struct {
	ID     uuid.UUID `json:"id"`
	Url    string    `json:"url"`
	Events []byte    `json:"events"`
	Active bool      `json:"active"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.ID,
		arg.Url,
		arg.Events,
		arg.Active,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.SecretEncrypted,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.ConsecutiveFailures,
	)
	return i, err
}
