// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimPendingSyncSessions = `-- name: ClaimPendingSyncSessions :many
SELECT id, project_id, user_id, note, started_at, ended_at, source, sync_state, sync_attempts, sync_next_at, sync_error, created_at, updated_at, deleted_at FROM work_sessions
WHERE sync_state = 'pending'
  AND deleted_at IS NULL
  AND ended_at IS NOT NULL
  AND (sync_next_at IS NULL OR sync_next_at <= $1::timestamptz)
ORDER BY sync_next_at ASC NULLS FIRST
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ClaimPendingSyncSessionsParams struct {
	Now time.Time `json:"now"`
	Lim int32     `json:"lim"`
}

func (q *Queries) ClaimPendingSyncSessions(ctx context.Context, arg ClaimPendingSyncSessionsParams) ([]WorkSession, error) {
	rows, err := q.db.Query(ctx, claimPendingSyncSessions, arg.Now, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkSession{}
	for rows.Next() {
		var i WorkSession
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Note,
			&i.StartedAt,
			&i.EndedAt,
			&i.Source,
			&i.SyncState,
			&i.SyncAttempts,
			&i.SyncNextAt,
			&i.SyncError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenWorkSession = `-- name: GetOpenWorkSession :one
SELECT id, project_id, user_id, note, started_at, ended_at, source, sync_state, sync_attempts, sync_next_at, sync_error, created_at, updated_at, deleted_at FROM work_sessions
WHERE user_id = $1 AND ended_at IS NULL AND deleted_at IS NULL
`

func (q *Queries) GetOpenWorkSession(ctx context.Context, userID uuid.UUID) (WorkSession, error) {
	row := q.db.QueryRow(ctx, getOpenWorkSession, userID)
	var i WorkSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Note,
		&i.StartedAt,
		&i.EndedAt,
		&i.Source,
		&i.SyncState,
		&i.SyncAttempts,
		&i.SyncNextAt,
		&i.SyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkSession = `-- name: GetWorkSession :one
SELECT id, project_id, user_id, note, started_at, ended_at, source, sync_state, sync_attempts, sync_next_at, sync_error, created_at, updated_at, deleted_at FROM work_sessions
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetWorkSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWorkSession(ctx context.Context, arg GetWorkSessionParams) (WorkSession, error) {
	row := q.db.QueryRow(ctx, getWorkSession, arg.ID, arg.UserID)
	var i WorkSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Note,
		&i.StartedAt,
		&i.EndedAt,
		&i.Source,
		&i.SyncState,
		&i.SyncAttempts,
		&i.SyncNextAt,
		&i.SyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWorkSessions = `-- name: ListWorkSessions :many
SELECT id, project_id, user_id, note, started_at, ended_at, source, sync_state, sync_attempts, sync_next_at, sync_error, created_at, updated_at, deleted_at FROM work_sessions
WHERE user_id = $1
  AND deleted_at IS NULL
  AND started_at < $2::timestamptz
  AND (ended_at IS NULL OR ended_at > $3::timestamptz)
  AND ($4::uuid IS NULL OR project_id = $4::uuid)
ORDER BY started_at DESC
`

type ListWorkSessionsParams struct {
	UserID    uuid.UUID  `json:"user_id"`
	ToTs      time.Time  `json:"to_ts"`
	FromTs    time.Time  `json:"from_ts"`
	ProjectID *uuid.UUID `json:"project_id"`
}

func (q *Queries) ListWorkSessions(ctx context.Context, arg ListWorkSessionsParams) ([]WorkSession, error) {
	rows, err := q.db.Query(ctx, listWorkSessions,
		arg.UserID,
		arg.ToTs,
		arg.FromTs,
		arg.ProjectID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkSession{}
	for rows.Next() {
		var i WorkSession
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Note,
			&i.StartedAt,
			&i.EndedAt,
			&i.Source,
			&i.SyncState,
			&i.SyncAttempts,
			&i.SyncNextAt,
			&i.SyncError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionSyncPending = `-- name: MarkSessionSyncPending :exec
UPDATE work_sessions
SET sync_state = 'pending', sync_next_at = now(), sync_attempts = 0, sync_error = NULL,
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type MarkSessionSyncPendingParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkSessionSyncPending(ctx context.Context, arg MarkSessionSyncPendingParams) error {
	_, err := q.db.Exec(ctx, markSessionSyncPending, arg.ID, arg.UserID)
	return err
}

const markSessionsSyncPendingSince = `-- name: MarkSessionsSyncPendingSince :execrows
UPDATE work_sessions
SET sync_state = 'pending', sync_next_at = now()
WHERE ended_at IS NOT NULL
  AND deleted_at IS NULL
  AND ended_at > $1::timestamptz
  AND sync_state IN ('ok', 'error')
`

func (q *Queries) MarkSessionsSyncPendingSince(ctx context.Context, since time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionsSyncPendingSince, since)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sessionCovering = `-- name: SessionCovering :one
SELECT id, project_id, user_id, note, started_at, ended_at, source, sync_state, sync_attempts, sync_next_at, sync_error, created_at, updated_at, deleted_at FROM work_sessions
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ended_at IS NOT NULL
  AND started_at <= $2::timestamptz
  AND ended_at >= $2::timestamptz
LIMIT 1
`

type SessionCoveringParams struct {
	UserID uuid.UUID `json:"user_id"`
	At     time.Time `json:"at"`
}

// Which session covers an instant. Ranges cannot overlap, so this returns at
// most one row.
func (q *Queries) SessionCovering(ctx context.Context, arg SessionCoveringParams) (WorkSession, error) {
	row := q.db.QueryRow(ctx, sessionCovering, arg.UserID, arg.At)
	var i WorkSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Note,
		&i.StartedAt,
		&i.EndedAt,
		&i.Source,
		&i.SyncState,
		&i.SyncAttempts,
		&i.SyncNextAt,
		&i.SyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setSessionSyncFailed = `-- name: SetSessionSyncFailed :exec
UPDATE work_sessions
SET sync_state = 'error',
    sync_attempts = sync_attempts + 1,
    sync_next_at = NULL,
    sync_error = $1
WHERE id = $2
`

type SetSessionSyncFailedParams struct {
	Err *string   `json:"err"`
	ID  uuid.UUID `json:"id"`
}

func (q *Queries) SetSessionSyncFailed(ctx context.Context, arg SetSessionSyncFailedParams) error {
	_, err := q.db.Exec(ctx, setSessionSyncFailed, arg.Err, arg.ID)
	return err
}

const setSessionSyncOK = `-- name: SetSessionSyncOK :exec
UPDATE work_sessions
SET sync_state = 'ok', sync_attempts = 0, sync_next_at = NULL, sync_error = NULL
WHERE id = $1
`

func (q *Queries) SetSessionSyncOK(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setSessionSyncOK, id)
	return err
}

const setSessionSyncRetry = `-- name: SetSessionSyncRetry :exec
UPDATE work_sessions
SET sync_state = 'pending',
    sync_attempts = sync_attempts + 1,
    sync_next_at = $1,
    sync_error = $2
WHERE id = $3
`

type SetSessionSyncRetryParams struct {
	NextAt *time.Time `json:"next_at"`
	Err    *string    `json:"err"`
	ID     uuid.UUID  `json:"id"`
}

func (q *Queries) SetSessionSyncRetry(ctx context.Context, arg SetSessionSyncRetryParams) error {
	_, err := q.db.Exec(ctx, setSessionSyncRetry, arg.NextAt, arg.Err, arg.ID)
	return err
}

const setSessionSyncSkipped = `-- name: SetSessionSyncSkipped :execrows
UPDATE work_sessions
SET sync_state = 'skipped', sync_next_at = NULL, sync_error = $1
WHERE user_id = $2 AND sync_state = 'pending'
`

type SetSessionSyncSkippedParams struct {
	Err    *string   `json:"err"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SetSessionSyncSkipped(ctx context.Context, arg SetSessionSyncSkippedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSessionSyncSkipped, arg.Err, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteWorkSession = `-- name: SoftDeleteWorkSession :execrows
UPDATE work_sessions SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteWorkSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteWorkSession(ctx context.Context, arg SoftDeleteWorkSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteWorkSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startWorkSession = `-- name: StartWorkSession :one
INSERT INTO work_sessions (id, project_id, user_id, note, started_at, source)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, user_id, note, started_at, ended_at, source, sync_state, sync_attempts, sync_next_at, sync_error, created_at, updated_at, deleted_at
`

type StartWorkSessionParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Note      string    `json:"note"`
	StartedAt time.Time `json:"started_at"`
	Source    string    `json:"source"`
}

func (q *Queries) StartWorkSession(ctx context.Context, arg StartWorkSessionParams) (WorkSession, error) {
	row := q.db.QueryRow(ctx, startWorkSession,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.Note,
		arg.StartedAt,
		arg.Source,
	)
	var i WorkSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Note,
		&i.StartedAt,
		&i.EndedAt,
		&i.Source,
		&i.SyncState,
		&i.SyncAttempts,
		&i.SyncNextAt,
		&i.SyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const stopOpenSessionForUser = `-- name: StopOpenSessionForUser :many
UPDATE work_sessions
SET ended_at = GREATEST($1::timestamptz, started_at + interval '1 microsecond'),
    updated_at = now(),
    sync_state = 'pending',
    sync_next_at = now(),
    sync_attempts = 0,
    sync_error = NULL
WHERE user_id = $2 AND ended_at IS NULL AND deleted_at IS NULL
RETURNING id, project_id, user_id, note, started_at, ended_at, source, sync_state, sync_attempts, sync_next_at, sync_error, created_at, updated_at, deleted_at
`

type StopOpenSessionForUserParams struct {
	At     time.Time `json:"at"`
	UserID uuid.UUID `json:"user_id"`
}

// Closes whichever session is currently open for this user. Called in the same
// transaction as StartWorkSession so a "start" that replaces a running timer is
// atomic: there is never an instant with two open sessions, which is what the
// one_open_session_per_user index would reject anyway.
//
// The GREATEST is the range CHECK's guard: ended_at must be strictly after
// started_at, so a stop that lands on (or before) the start is nudged one
// microsecond forward rather than failing. A microsecond, not a second — with a
// second, replacing a timer less than a second old would push its end PAST the
// new session's start and the two would overlap, which is exactly what commit
// attribution cannot survive. The caller reads the returned ended_at back and
// starts the next session there, so the two abut exactly.
func (q *Queries) StopOpenSessionForUser(ctx context.Context, arg StopOpenSessionForUserParams) ([]WorkSession, error) {
	rows, err := q.db.Query(ctx, stopOpenSessionForUser, arg.At, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkSession{}
	for rows.Next() {
		var i WorkSession
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Note,
			&i.StartedAt,
			&i.EndedAt,
			&i.Source,
			&i.SyncState,
			&i.SyncAttempts,
			&i.SyncNextAt,
			&i.SyncError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stopWorkSession = `-- name: StopWorkSession :one
UPDATE work_sessions
SET ended_at = GREATEST($1::timestamptz, started_at + interval '1 microsecond'),
    updated_at = now(),
    sync_state = 'pending',
    sync_next_at = now(),
    sync_attempts = 0,
    sync_error = NULL
WHERE id = $2 AND user_id = $3
  AND ended_at IS NULL AND deleted_at IS NULL
RETURNING id, project_id, user_id, note, started_at, ended_at, source, sync_state, sync_attempts, sync_next_at, sync_error, created_at, updated_at, deleted_at
`

type StopWorkSessionParams struct {
	At     time.Time `json:"at"`
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) StopWorkSession(ctx context.Context, arg StopWorkSessionParams) (WorkSession, error) {
	row := q.db.QueryRow(ctx, stopWorkSession, arg.At, arg.ID, arg.UserID)
	var i WorkSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Note,
		&i.StartedAt,
		&i.EndedAt,
		&i.Source,
		&i.SyncState,
		&i.SyncAttempts,
		&i.SyncNextAt,
		&i.SyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const summaryByDay = `-- name: SummaryByDay :many
SELECT
    to_char(date_trunc('day', ws.started_at AT TIME ZONE $1::text), 'YYYY-MM-DD') AS day,
    sum(extract(epoch FROM (
        least(ws.ended_at, $2::timestamptz)
      - greatest(ws.started_at, $3::timestamptz)
    )))::bigint AS seconds
FROM work_sessions ws
WHERE ws.user_id = $4
  AND ws.deleted_at IS NULL
  AND ws.ended_at IS NOT NULL
  AND ws.started_at < $2::timestamptz
  AND ws.ended_at > $3::timestamptz
GROUP BY 1
ORDER BY 1 ASC
`

type SummaryByDayParams struct {
	Tz     string    `json:"tz"`
	ToTs   time.Time `json:"to_ts"`
	FromTs time.Time `json:"from_ts"`
	UserID uuid.UUID `json:"user_id"`
}

type SummaryByDayRow struct {
	Day     string `json:"day"`
	Seconds int64  `json:"seconds"`
}

// Day buckets are cut in the caller's timezone, not UTC: a session that runs
// 22:30–23:30 UTC belongs to the next local day in Istanbul, and a report that
// says otherwise is simply wrong to the person reading it.
func (q *Queries) SummaryByDay(ctx context.Context, arg SummaryByDayParams) ([]SummaryByDayRow, error) {
	rows, err := q.db.Query(ctx, summaryByDay,
		arg.Tz,
		arg.ToTs,
		arg.FromTs,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummaryByDayRow{}
	for rows.Next() {
		var i SummaryByDayRow
		if err := rows.Scan(&i.Day, &i.Seconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryByProject = `-- name: SummaryByProject :many

SELECT
    p.id            AS project_id,
    p.name          AS project_name,
    p.client        AS client,
    p.currency      AS currency,
    p.billable      AS billable,
    p.hourly_rate_cents AS hourly_rate_cents,
    sum(extract(epoch FROM (
        least(ws.ended_at, $1::timestamptz)
      - greatest(ws.started_at, $2::timestamptz)
    )))::bigint AS seconds
FROM work_sessions ws
JOIN projects p ON p.id = ws.project_id
WHERE ws.user_id = $3
  AND ws.deleted_at IS NULL
  AND ws.ended_at IS NOT NULL
  AND ws.started_at < $1::timestamptz
  AND ws.ended_at > $2::timestamptz
GROUP BY p.id, p.name, p.client, p.currency, p.billable, p.hourly_rate_cents
ORDER BY seconds DESC
`

type SummaryByProjectParams struct {
	ToTs   time.Time `json:"to_ts"`
	FromTs time.Time `json:"from_ts"`
	UserID uuid.UUID `json:"user_id"`
}

type SummaryByProjectRow struct {
	ProjectID       uuid.UUID `json:"project_id"`
	ProjectName     string    `json:"project_name"`
	Client          string    `json:"client"`
	Currency        string    `json:"currency"`
	Billable        bool      `json:"billable"`
	HourlyRateCents *int64    `json:"hourly_rate_cents"`
	Seconds         int64     `json:"seconds"`
}

// Reports ------------------------------------------------------------------
func (q *Queries) SummaryByProject(ctx context.Context, arg SummaryByProjectParams) ([]SummaryByProjectRow, error) {
	rows, err := q.db.Query(ctx, summaryByProject, arg.ToTs, arg.FromTs, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummaryByProjectRow{}
	for rows.Next() {
		var i SummaryByProjectRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ProjectName,
			&i.Client,
			&i.Currency,
			&i.Billable,
			&i.HourlyRateCents,
			&i.Seconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkSession = `-- name: UpdateWorkSession :one
UPDATE work_sessions SET
    project_id = coalesce($1, project_id),
    note       = coalesce($2, note),
    started_at = coalesce($3, started_at),
    ended_at   = CASE WHEN $4::boolean THEN $5
                      ELSE ended_at END,
    updated_at = now()
WHERE id = $6 AND user_id = $7 AND deleted_at IS NULL
RETURNING id, project_id, user_id, note, started_at, ended_at, source, sync_state, sync_attempts, sync_next_at, sync_error, created_at, updated_at, deleted_at
`

type UpdateWorkSessionParams struct {
	ProjectID *uuid.UUID `json:"project_id"`
	Note      *string    `json:"note"`
	StartedAt *time.Time `json:"started_at"`
	SetEnded  bool       `json:"set_ended"`
	EndedAt   *time.Time `json:"ended_at"`
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
}

func (q *Queries) UpdateWorkSession(ctx context.Context, arg UpdateWorkSessionParams) (WorkSession, error) {
	row := q.db.QueryRow(ctx, updateWorkSession,
		arg.ProjectID,
		arg.Note,
		arg.StartedAt,
		arg.SetEnded,
		arg.EndedAt,
		arg.ID,
		arg.UserID,
	)
	var i WorkSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Note,
		&i.StartedAt,
		&i.EndedAt,
		&i.Source,
		&i.SyncState,
		&i.SyncAttempts,
		&i.SyncNextAt,
		&i.SyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
